---

- name: Install the Webtatic Repo
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: present
  become: yes

- name: Remove PHP if installed
  yum:
    pkg: "php*"
    state: removed
  become: yes

- name: Install other required packages
  yum:
    pkg: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - epel-release
    - "@Development Tools"
    - ant
    - unzip
    - mlocate
    - htop
    - cowsay
    - supervisor

- name: Install php
  yum:
    pkg: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - php70w
    - php70w-cli.x86_64
    - php70w-common.x86_64
    - php70w-devel.x86_64
    - php70w-fpm.x86_64
    - php70w-ldap.x86_64
    - php70w-mbstring.x86_64
    - php70w-mcrypt.x86_64
    - php70w-odbc.x86_64
    - php70w-opcache.x86_64
    - php70w-pdo.x86_64
    - php70w-pdo_dblib.x86_64
    - php70w-pear.noarch
    - php70w-phpdbg.x86_64
    - php70w-pspell.x86_64
    - php70w-soap.x86_64
    - php70w-xml.x86_64
    - php70w-xmlrpc.x86_64